name: PC1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - sqlite
  - jupyter
  - matplotlib
  - seaborn
  - pip
  - pip:
      - jsonlines
      - requests
